ecomapp/urls.py
from django.urls import path
from .views import *
from . import views


app_name = "ecomapp"
urlpatterns = [

    # Client side pages
    path("", HomeView.as_view(), name="home"),
    path("about/", AboutView.as_view(), name="about"),
    path("contact-us/", ContactView.as_view(), name="contact"),
    path("all-products/", AllProductsView.as_view(), name="allproducts"),
    path("product/<slug:slug>/", ProductDetailView.as_view(), name="productdetail"),
    path("stores/",views.getStore,name="stores"),

    path("add-to-cart-<int:pro_id>/", AddToCartView.as_view(), name="addtocart"),
    path("my-cart/", MyCartView.as_view(), name="mycart"),
    path("manage-cart/<int:cp_id>/", ManageCartView.as_view(), name="managecart"),
    path("empty-cart/", EmptyCartView.as_view(), name="emptycart"),

    path("checkout/", CheckoutView.as_view(), name="checkout"),

    path("khalti-request/", KhaltiRequestView.as_view(), name="khaltirequest"),
    path("khalti-verify/", KhaltiVerifyView.as_view(), name="khaltiverify"),

    path("esewa-request/", EsewaRequestView.as_view(), name="esewarequest"),
    path("esewa-verify/", EsewaVerifyView.as_view(), name="esewaverify"),

    path("register/",
         CustomerRegistrationView.as_view(), name="customerregistration"),

    path("logout/", CustomerLogoutView.as_view(), name="customerlogout"),
    path("login/", CustomerLoginView.as_view(), name="customerlogin"),

    path("profile/", CustomerProfileView.as_view(), name="customerprofile"),
    path("profile/order-<int:pk>/", CustomerOrderDetailView.as_view(),
         name="customerorderdetail"),

    path("search/", SearchView.as_view(), name="search"),

    path("forgot-password/", PasswordForgotView.as_view(), name="passworforgot"),
    path("password-reset/<email>/<token>/",
         PasswordResetView.as_view(), name="passwordreset"),
    # Admin Side pages

    path("admin-login/", AdminLoginView.as_view(), name="adminlogin"),
    path("admin-home/", AdminHomeView.as_view(), name="adminhome"),
    path("admin-order/<int:pk>/", AdminOrderDetailView.as_view(),
         name="adminorderdetail"),

    path("admin-all-orders/", AdminOrderListView.as_view(), name="adminorderlist"),

    path("admin-order-<int:pk>-change/",
         AdminOrderStatuChangeView.as_view(), name="adminorderstatuschange"),

    path("admin-product/list/", AdminProductListView.as_view(),
         name="adminproductlist"),
    path("admin-product/add/", AdminProductCreateView.as_view(),
         name="adminproductcreate"),
    path('KLUStat',views.KLStat,name="klu_stat"),
    path('KLU_Groc',views.KLGroc,name="klu_groc"),

    path('Gtr_Groc',views.GtrGroc,name="gtr_groc"),
    path('gtr_stat',views.GtrStat,name="gtr_stat"),
    path('Gtr_electronics',views.GtrElec,name="gtr_elec"),
    path('Gtr_Cloth',views.GtrCloth,name="gtr_cloth"),
    path('Gtr_Home',views.GtrHome,name="gtr_home"),

    path('Vjw_Groc',views.VjwGroc,name="vjw_groc"),
    path('Vjw_stat',views.VjwStat,name="vjw_stat"),
    path('Vjw_elec',views.VjwElec,name="vjw_elec"),
    path('Vjw_Cloth',views.VjwCloth,name="vjw_cloth"),
    path('Vjw_Home',views.VjwHome,name="vjw_home"),
    path('pie_chart',views.pie_chart,name="pie_chart"),
    path('stationery',views.StationaryProducts,name="stationary"),
    path('category/<str:cat>',views.GetCategory,name="get_category"),
    #path('category/<str:cat>',views.filter_data,name='filter_data'),
    path('sort_lh/<str:cat>',views.sort_lh,name="sort_lh"),
    path('sort_hl/<str:cat>',views.sort_hl,name="sort_hl"),
]

ecomproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("ecomapp.urls")),
    #path('api', views.ChartData.as_view())
    #path('KLUStat',KLStat,name="klu_stat"),

]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/Gtr_Home.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" href="{% url 'ecomapp:home' %}">At Your Doorstep</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'ecomapp:home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'ecomapp:allproducts' %}">Products</a>
            </li>

            <li class="nav_item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown1" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Categories
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="/category/Provisions">Provisions</a>
                <a class="dropdown-item" href="/category/Stationery">Stationery</a>
                <a class="dropdown-item" href="/category/Electronic Gadgets">Electronics</a>
                <a class="dropdown-item" href="/category/Clothing and Fashion">Clothing & Fashion</a>
                <a class="dropdown-item" href="/category/Home Care & Furniture">Home Care & Furniture</a>
                </div>
            </li>


            <li class="nav-item">
                <a class="nav-link" href="{% url 'ecomapp:pie_chart' %}">Dashboard</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{% url 'ecomapp:mycart' %}">Cart</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'ecomapp:stores' %}">Stores</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                My Account
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                {% if request.user.customer %}
                <a class="dropdown-item" href="{% url 'ecomapp:customerprofile' %}">My Profile</a>
                <a class="dropdown-item" href="{% url 'ecomapp:customerlogout' %}">Logout</a>
                {% else %}
                <a class="dropdown-item" href="{% url 'ecomapp:customerregistration' %}">Register</a>
                <a class="dropdown-item" href="{% url 'ecomapp:customerlogin' %}">Login</a>
                {% endif %}
                </div>
            </li>
            </ul>
            <form class="form-inline my-2 my-lg-0" action="{% url 'ecomapp:search' %}" method="GET">
            <input id="myInput" name="keyword" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" required>
            <button class="btn btn-danger my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
        </nav>
    <hr>


    {% block content %}
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>

</html><!DOCTYPE html>
<html>
<head>
<style>
div.gallery {
  margin: 5px;
  border: 1px solid #ccc;
  float: left;
  width: 180px;
}

div.gallery:hover {
  border: 1px solid #777;
}

div.gallery img {
  width: 100%;
  height: auto;
}

div.desc {
  padding: 15px;
  text-align: center;
}

.button {
        display: inline-block;
        padding: 10px 20px;
        text-align: center;
        text-decoration: none;
        color: #ffffff;
        background-color: #7aa8b7;
        border-radius: 6px;
        outline: none;
</style>
</head>
<body>

<div class="gallery">
  <a target="_blank" href="https://threebestrated.in/images/RelianceDigital-Guntur-AP.png">
    <img src="https://threebestrated.in/images/RelianceDigital-Guntur-AP.png" alt="V9" width="600" height="400">
  </a>
  <div class="desc"><p><b>Reliance Digital</b></p>
      Ultimate stop for all the house appliance needs</div>
     <center><a href="/category/Home Care & Furniture" class="button">Shop</a></center>
</div>

<div class="gallery">
  <a target="_blank" href="https://www.tringcity.in/oc-content/uploads/33/29663.jpg">
    <img src="https://www.tringcity.in/oc-content/uploads/33/29663.jpg" alt="Bajaj" width="600" height="400">
  </a>
  <div class="desc"><p><b>Bajaj Electronics</b></p>
      A great destination for customers who wish to transform themselves digitally</div>
     <center><a href="/category/Home Care & Furniture" class="button">Shop</a></center>
</div>

<div class="gallery">
  <a target="_blank" href="https://content.jdmagicbox.com/comp/guntur/p8/9999px863.x863.120125154018.t6p8/catalogue/ramachandra-brothers-laxmipuram-guntur-furniture-dealers-1co9xalpqx.jpg">
    <img src="https://content.jdmagicbox.com/comp/guntur/p8/9999px863.x863.120125154018.t6p8/catalogue/ramachandra-brothers-laxmipuram-guntur-furniture-dealers-1co9xalpqx.jpg" alt="RCB" width="600" height="400">
  </a>
  <div class="desc"><p><b>Rama Chandra Brothers</b></p>
      Mega furniture palace to redefine housing</div>
     <center><a href="/category/Home Care & Furniture" class="button">Shop</a></center>
</div>

<div class="gallery">
  <a target="_blank" href="https://threebestrated.in/images/Damro-Guntur-AP.jpeg">
    <img src="https://threebestrated.in/images/Damro-Guntur-AP.jpeg" alt="Damro" width="600" height="400">
  </a>
  <div class="desc"><p><b>Damro</b></p>
      A great collection of all kinds of furniture</div>
     <center><a href="/category/Home Care & Furniture" class="button">Shop</a></center>
</div>
</body>
</html>

templates/Tadepalli.html
<div class="card">
    <div class="bg-image hover-overlay ripple" data-mdb-ripple-color="light">
      <img
        src="https://mdbootstrap.com/img/new/standard/nature/111.jpg"
        class="img-fluid"
      />
      <a href="#!">
        <div class="mask" style="background-color: rgba(251, 251, 251, 0.15)"></div>
      </a>
    </div>
    <div class="card-body">
      <h5 class="card-title">Card title</h5>
      <p class="card-text">
        Some quick example text to build on the card title and make up the bulk of the
        card's content.
      </p>
      <a href="#!" class="btn btn-primary">Button</a>
    </div>
  </div>

templates/Vjw_Home.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" href="{% url 'ecomapp:home' %}">At Your Doorstep</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'ecomapp:home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'ecomapp:allproducts' %}">Products</a>
            </li>

            <li class="nav_item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown1" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Categories
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="/category/Provisions">Provisions</a>
                <a class="dropdown-item" href="/category/Stationery">Stationery</a>
                <a class="dropdown-item" href="/category/Electronic Gadgets">Electronics</a>
                <a class="dropdown-item" href="/category/Clothing and Fashion">Clothing & Fashion</a>
                <a class="dropdown-item" href="/category/Home Care & Furniture">Home Care & Furniture</a>
                </div>
            </li>


            <li class="nav-item">
                <a class="nav-link" href="{% url 'ecomapp:pie_chart' %}">Dashboard</a>
            </li>

            <li class="nav-item">
                <a class="nav-link" href="{% url 'ecomapp:mycart' %}">Cart</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'ecomapp:stores' %}">Stores</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                My Account
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                {% if request.user.customer %}
                <a class="dropdown-item" href="{% url 'ecomapp:customerprofile' %}">My Profile</a>
                <a class="dropdown-item" href="{% url 'ecomapp:customerlogout' %}">Logout</a>
                {% else %}
                <a class="dropdown-item" href="{% url 'ecomapp:customerregistration' %}">Register</a>
                <a class="dropdown-item" href="{% url 'ecomapp:customerlogin' %}">Login</a>
                {% endif %}
                </div>
            </li>
            </ul>
            <form class="form-inline my-2 my-lg-0" action="{% url 'ecomapp:search' %}" method="GET">
            <input id="myInput" name="keyword" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" required>
            <button class="btn btn-danger my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
        </nav>
    <hr>


    {% block content %}
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>

</html>
<!DOCTYPE html>
<html>
<head>
<style>
div.gallery {
  margin: 5px;
  border: 1px solid #ccc;
  float: left;
  width: 180px;
}

div.gallery:hover {
  border: 1px solid #777;
}

div.gallery img {
  width: 100%;
  height: auto;
}

div.desc {
  padding: 15px;
  text-align: center;
}

.button {
        display: inline-block;
        padding: 10px 20px;
        text-align: center;
        text-decoration: none;
        color: #ffffff;
        background-color: #7aa8b7;
        border-radius: 6px;
        outline: none;
</style>
</head>
<body>


<div class="gallery">
  <a target="_blank" href="https://threebestrated.in/images/TirumalaMusicCentrePLtd-Vijayawada-AP.png">
    <img src="https://threebestrated.in/images/TirumalaMusicCentrePLtd-Vijayawada-AP.png" alt="TMC" width="600" height="400">
  </a>
  <div class="desc"><p><b>Tirumala Music Centre</b></p>
      Best place for changing your housing experience</div>
     <center><a href="/category/Home Care & Furniture" class="button">Shop</a></center>
</div>

<div class="gallery">
  <a target="_blank" href="https://content3.jdmagicbox.com/comp/vijayawada/89/0866p866std2000089/catalogue/ghar-sansar-governerpet-vijayawada-gift-shops-0zdlghiazk.jpg?clr=333333">
    <img src="https://content3.jdmagicbox.com/comp/vijayawada/89/0866p866std2000089/catalogue/ghar-sansar-governerpet-vijayawada-gift-shops-0zdlghiazk.jpg?clr=333333" alt="GS" width="600" height="400">
  </a>
  <div class="desc"><p><b>Ghar Sansar</b></p>
      One stop for all home needs</div>
     <center><a href="/category/Home Care & Furniture" class="button">Shop</a></center>
</div>

<div class="gallery">
  <a target="_blank" href="https://content.jdmagicbox.com/comp/guntur/p8/9999px863.x863.120125154018.t6p8/catalogue/ramachandra-brothers-laxmipuram-guntur-furniture-dealers-1co9xalpqx.jpg">
    <img src="https://content.jdmagicbox.com/comp/guntur/p8/9999px863.x863.120125154018.t6p8/catalogue/ramachandra-brothers-laxmipuram-guntur-furniture-dealers-1co9xalpqx.jpg" alt="RCB" width="600" height="400">
  </a>
  <div class="desc"><p><b>Rama Chandra Brothers</b></p>
      Mega furniture palace to redefine housing</div>
     <center><a href="/category/Home Care & Furniture" class="button">Shop</a></center>
</div>

<div class="gallery">
  <a target="_blank" href="https://threebestrated.in/images/FurniturePark-Vijayawada-AP.jpeg">
    <img src="https://threebestrated.in/images/FurniturePark-Vijayawada-AP.jpeg" alt="Furniture Park" width="600" height="400">
  </a>
  <div class="desc"><p><b>Furniture Park</b></p>
      A great collection of all kinds of furniture</div>
     <center><a href="/category/Home Care & Furniture" class="button">Shop</a></center>
</div>
</body>
</html>

templates/addtocart.html
{% extends 'base.html' %}

{% block title %}Add to cart{% endblock %}

{% block content %}
<div class="container">
    <h3>Product added to cart successfully.</h3>
</div>
{% endblock %}

templates/passwordreset.html
{% extends 'base.html' %}

{% block title %}Reset password{% endblock %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-8">
            <form action="" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button>Reset password</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

templates/stores.html
{% extends 'base.html' %}
{% load static %}
{% block title %} All Products {% endblock %}

{% block content %}
<div class="container" >
    <h3>Locations</h3><hr>

<div>

<p>In this section, some stores based in the locality of the following three places are made available to choose from for purchasing:</p><br>
<!DOCTYPE html>
<html>
<head>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
	<style>
	#map {
		height: 300px;
		width: 50%;
	}
	.button {
        display: inline-block;
        padding: 10px 20px;
        text-align: center;
        text-decoration: none;
        color: #ffffff;
        background-color: #7aa8b7;
        border-radius: 6px;
        outline: none;
	</style>
</head>
<body>
	<!-- Tadepalli-->
	<h3>Stores near by KL University</h3>
	<div id1="map"></div>
	<img src="https://images.shiksha.com/mediadata/images/1537422868phpP1eDGz.jpeg" alt="KL University Image" style="width:900px;height:500px;"><br><br>
	<!--<script>
	function initMap() {
		var uluru = {lat: 16.4799, lng: 80.6174};
		var map = new google.maps.Map(document.getElementById('map'), {
		zoom: 6,
		center: uluru
		});
		var marker = new google.maps.Marker({
		position: uluru,
		map: map
		});
	}
	</script>
	<div class="card">
    <div>
      <img src="">
      <a href="#!">
        <div class="mask" style="background-color: rgba(251, 251, 251, 0.15)"></div>
      </a>
    </div>
  </div>
	<script async defer
	src=
"https://maps.googleapis.com/maps/api/js?key=
AIzaSyB2bXKNDezDf6YNVc-SauobynNHPo4RJb8&callback=initMap">
	</script>-->
	<ul>
		<li><a href="{% url 'ecomapp:klu_groc'%}">Provisions</a></li>
		<li><a href="{% url 'ecomapp:klu_stat'%}">Stationery</a></li>
	</ul>

<!-- Guntur--><br><br>
<h3>Stores near by Guntur</h3>
	<div id1="map"></div>
	<img src="https://images.newindianexpress.com/uploads/user/imagelibrary/2020/4/13/w900X450/Guntur_EPS.jpg" alt="Guntur Image"><br><br>
	<!--<script>
	function initMap() {
		var uluru = {lat: 16.4799, lng: 80.6174};
		var map = new google.maps.Map(document.getElementById('map'), {
		zoom: 6,
		center: uluru
		});
		var marker = new google.maps.Marker({
		position: uluru,
		map: map
		});
	}
	</script>
	<div class="card">
    <div>
      <img src="">
      <a href="#!">
        <div class="mask" style="background-color: rgba(251, 251, 251, 0.15)"></div>
      </a>
    </div>
  </div>
	<script async defer
	src=
"https://maps.googleapis.com/maps/api/js?key=
AIzaSyB2bXKNDezDf6YNVc-SauobynNHPo4RJb8&callback=initMap">
	</script>-->
	<ul>
		<li><a href="{% url 'ecomapp:gtr_groc'%}">Provisions</a></li>
		<li><a href="{% url 'ecomapp:gtr_stat'%}">Stationery</a></li>
		<li><a href="{% url 'ecomapp:gtr_elec'%}">Electronics</a></li>
		<li><a href="{% url 'ecomapp:gtr_cloth'%}">Clothing & Fashion</a></li>
		<li><a href="{% url 'ecomapp:gtr_home'%}">Home Care & Furniture</a></li>
	</ul>
	<!-- Vijayawada-->
	<br><br>
<h3>Stores in Vijayawada</h3>
	<div id1="map"></div>
	<img
		src="https://www.thenewsminute.com/sites/default/files/styles/slideshow_image_size/public/Vijayawada_aerial_shot_screengrab_1200x800.jpg?itok=JhijsMN2" style="width:900px;height:500px;" alt="Vijayawada Image">
		<br><br><!-- <script>
	function initMap() {
		var uluru = {lat: 16.4799, lng: 80.6174};
		var map = new google.maps.Map(document.getElementById('map'), {
		zoom: 6,
		center: uluru
		});
		var marker = new google.maps.Marker({
		position: uluru,
		map: map
		});
	}
	</script>-->
	<ul>
		<li><a href="{% url 'ecomapp:vjw_groc'%}">Provisions</a></li>
		<li><a href="{% url 'ecomapp:vjw_stat'%}">Stationery</a></li>
		<li><a href="{% url 'ecomapp:vjw_elec'%}">Electronics</a></li>
		<li><a href="{% url 'ecomapp:vjw_cloth'%}">Clothing & Fashion</a></li>
		<li><a href="{% url 'ecomapp:vjw_home'%}">Home Care & Furniture</a></li>
	</ul>
	<!--<div class="card">
    <div>
      <img src="">
      <a href="#!">
        <div class="mask" style="background-color: rgba(251, 251, 251, 0.15)"></div>
      </a>
    </div>
  </div>
	<script async defer
	src=
"https://maps.googleapis.com/maps/api/js?key=
AIzaSyB2bXKNDezDf6YNVc-SauobynNHPo4RJb8&callback=initMap">
	</script>-->

<br><br>
</body>
</html>
<!-- Map Files
<!DOCTYPE html>
<html>
<head>
	<style>
	#map {
		height: 300px;
		width: 50%;
	}
	</style>
</head>
<body>
	<h3>GFG Google Maps Demo</h3>
	<div id2="map"></div>
	<script>
	function initMap() {
		var uluru = {lat: 16.3067, lng: 80.4365};
		var map = new google.maps.Map(document.getElementById('map'), {
		zoom: 6,
		center: uluru
		});
		var marker = new google.maps.Marker({
		position: uluru,
		map: map
		});
	}
	</script>
	<script async defer
	src=
"https://maps.googleapis.com/maps/api/js?key=
AIzaSyB2bXKNDezDf6YNVc-SauobynNHPo4RJb8&callback=initMap">
	</script>
</body>
</html>

<!DOCTYPE html>
<html>
<head>
	<style>
	#map {
		height: 300px;
		width: 50%;
	}
	</style>
</head>
<body>
	<h3>GFG Google Maps Demo</h3>
	<div id="map"></div>
	<script>
	function initMap() {
		var uluru = {lat: 16.5062, lng: 80.6480};
		var map = new google.maps.Map(document.getElementById('map'), {
		zoom: 6,
		center: uluru
		});
		var marker = new google.maps.Marker({
		position: uluru,
		map: map
		});
	}
	</script>
	<script async defer
	src=
"https://maps.googleapis.com/maps/api/js?key=
AIzaSyB2bXKNDezDf6YNVc-SauobynNHPo4RJb8&callback=initMap">
	</script>
</body>
</html>

</div>
-->
	<!DOCTYPE html>
<html>
<head>
  <style>
  #map {
    height: 300px;
    width: 50%;
  }
  </style>
</head>
<body>
  <h3> Google Maps </h3>
  <div id="map"></div>
  <script>
  function initMap() {
    var uluru = {lat: 16.5062, lng: 80.6480};
    var map = new google.maps.Map(document.getElementById('map'), {
    zoom: 6,
    center: uluru
    });
    var marker = new google.maps.Marker({
    position: uluru,
    map: map
    });
  }
  </script>
  <script async defer
  src=
"https://maps.googleapis.com/maps/api/js?key=
AIzaSyB2bXKNDezDf6YNVc-SauobynNHPo4RJb8&callback=initMap">
  </script>
</body>
</html>

</div>
{% endblock %}

</div>
</div>